### ISSUE TITLE
Migrate to piwik/devite-detector

### ISSUE THREAD

**Issue by benji07** [Elao/ElaoBrowserDetector#4]
I think we need to use https://github.com/piwik/device-detector instead of browsecap

**Comment by grizzlylab** [comment]
If you decide to do it, would be nice to be able to choose "browscap" or "device-detector" in a config file.

**Comment by ghost** [comment]
I just noticed that our site seriously slowed down after we integrated this library. I did not now, that a simple PHP function like get_browser() could be that ridicuously slow:
https://bugs.php.net/bug.php?id=70490

get_browser is not usable. period. Also see the comment at the top of its source code:
https://github.com/php/php-src/blob/0787cd60ed3d0c8c8c8ff7e49b9bb3587bf33b64/ext/standard/browscap.c#L51

Maybe as a first step migrate to this library which should be a compatible replacement for get_browser:
https://github.com/browscap/browscap-php

**Comment by grizzlylab** [comment]
I totally agree with you, that's why I removed this library from my project. On simple pages, it added 500 ms...
